shared_config: configs/shared.yaml

features:
  features1:
    config: configs/features1.yaml
  features2:
    config: configs/features2.yaml

models:
  xgboost:
    config: configs/xgboost.yaml
  random_forest:
    config: configs/random_forest.yaml

tracking:
  experiment_name_prefix: Hotel_No_Show
  tracking_uri: sqlite:///mlflow.db

outputs:
  reports_dir: reports/model
